
order_id_request_text: Enter your order without a V character 

export_rack:
  path: /defauld/export/excel
  columns: [machine_type, kast_nr, kaart_id, kaart_type, pagina_nr, address]
  elements_to_request:
   - variable: order_id
     text: Enter your order without a V character
     variable_type: int

  file_elements: [Rack opbouw] 
  file_exclude_elements: [] 
  extension_type: .xlsx


export_io:
  path: /defauld/export/excel
  columns: [machine_type, kast_nr, pagina_nr, kaart_id, kaart_port, port_info, info]
  elements_to_request:
   - variable: order_id
     text: Enter your order without a V character
     variable_type: int

  file_elements: [IO lijst] 
  file_exclude_elements: [] 
  extension_type: .xlsx


export_schematic:
  path: /defauld/export/schematic
  elements_to_request:
   - variable: order_id
     text: Enter your order without a V character
     variable_type: int

  file_elements: [] 
  file_exclude_elements: [Changes] 
  extension_type: .pdf

  jpg_format: '%machine_type%_%kast_nr%_%pagina_nr%'
  jpg_pages_to_exclude: [LIST]

#X = horizontaal
#Y = verticaal 

elements:
  lamp:
      X_length: 50 
      Y_length: 50
  button:
      X_length: 50 
      Y_length: 50
  text:
      X_length: 50 
      Y_length: 50
  input:
      X_length: 50 
      Y_length: 50

page_section:
  Y_pos: 100 
  X_pos: [9, 24, 24, 24, 24, 24, 24, 24, 24, 9]
  element_pos: 33 

page_nr:
    box:
    X_pos: 829 
    Y_pos: 854
    X_length: 45
    Y_length: 339 
    format: =%machine_type%+%kast_nr%/%pagina_nr%

box_page_nr:
  X_pos: 829 
  Y_pos: 854
  X_length: 45
  Y_length: 339 








